# Generated by Django 5.2 on 2025-06-01 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0005_booking_is_cancelled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yacht',
            name='concept',
        ),
        migrations.RemoveField(
            model_name='yacht',
            name='country',
        ),
        migrations.RemoveField(
            model_name='yacht',
            name='design_style',
        ),
        migrations.RemoveField(
            model_name='yacht',
            name='hull_material',
        ),
        migrations.RemoveField(
            model_name='yacht',
            name='hull_type',
        ),
        migrations.RemoveField(
            model_name='yacht',
            name='model_name',
        ),
        migrations.RemoveField(
            model_name='yacht',
            name='release_period',
        ),
        migrations.RemoveField(
            model_name='yacht',
            name='seaworthiness_class',
        ),
        migrations.RemoveField(
            model_name='yacht',
            name='series',
        ),
        migrations.RemoveField(
            model_name='yacht',
            name='shipyard',
        ),
    ]
