# Generated by Django 5.2 on 2025-06-22 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0006_remove_yacht_concept_remove_yacht_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yacht',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='yacht',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True),
        ),
    ]
