# Generated by Django 5.2 on 2025-06-23 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0008_alter_yacht_latitude_alter_yacht_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='reject_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'В ожидании'), ('processing', 'В обработке'), ('accepted', 'Принято'), ('rejected', 'Отклонено')], default='pending', max_length=20),
        ),
    ]
